# Generated by Django 4.2.30 on 2026-04-27 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='invited_email',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
