[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi --workers 2 --threads 2 --log-file -"
preDeployCommand = "python manage.py migrate --noinput && python manage.py make_staff pandyakaran95@gmail.com"
healthcheckPath = "/api/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
